from pathlib import Path
p=Path('docs/index.html')
s=p.read_text(encoding='utf-8')

def r(old,new,n=1):
    global s
    if old not in s: raise SystemExit('Falta patrón: '+old[:100])
    s=s.replace(old,new,n)

r('</style>', '''  .delivery-radius-notice{margin:0 0 10px;padding:10px 11px;border:1px solid #b9d9ef;border-radius:12px;background:#eef8ff;color:#31536e;font-size:.67rem;line-height:1.42}.delivery-radius-notice strong{display:block;color:#075f9a;margin-bottom:4px}.delivery-radius-notice.warning{border-color:#f1cc82;background:#fff7df;color:#76520f}.delivery-radius-notice.ok{border-color:#b9e2cf;background:#eefaf4;color:#166447}.delivery-radius-notice.error{border-color:#efbdc6;background:#fff1f3;color:#9d2940}.delivery-location-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-top:7px}.delivery-location-actions button{border:1px solid #bfd6e8;background:#fff;color:#0b66ae;border-radius:9px;padding:6px 9px;font-size:.61rem;font-weight:900}.delivery-location-status{font-weight:800}.success-privacy-note{margin:10px 0 0;padding:9px 10px;border-radius:11px;background:#eef8f4;color:#166447;font-size:.67rem;font-weight:800;line-height:1.4}\n</style>''')
r('<p class="privacy-note">Tus datos no se publican en el catálogo. Solo se usan para identificar los pedidos que tú envíes a esta farmacia.</p>', '<p class="privacy-note">Tus datos de contacto se conservan únicamente en este dispositivo para identificar tus pedidos y viajan cifrados a la farmacia. La dirección y la fotografía de entrega se retiran del visor después de enviar.</p>')
r('''      <div class="checkout-grid">\n        <label>Nombre completo<input id="customerName" autocomplete="name" maxlength="80" placeholder="Tu nombre"></label>\n        <label>Teléfono<input id="customerPhone" autocomplete="tel" inputmode="tel" maxlength="20" placeholder="10 dígitos"></label>\n        <label class="full">Observaciones<textarea id="customerNote" maxlength="240" placeholder="Opcional: indicaciones para la farmacia"></textarea></label>\n      </div>''', '''      <div class="checkout-grid">\n        <input id="customerName" type="hidden"><input id="customerPhone" type="hidden">\n        <div class="privacy-note full">🔒 Tus datos de contacto ya están registrados en este dispositivo y se enviarán cifrados a la farmacia. No se muestran nuevamente al finalizar el carrito.</div>\n        <label class="full">Observaciones<textarea id="customerNote" maxlength="240" placeholder="Opcional: indicaciones para la farmacia"></textarea></label>\n      </div>''')
r('<div id="homeDeliveryFields" class="delivery-section" hidden>\n          <label>Dirección de entrega', '''<div id="homeDeliveryFields" class="delivery-section" hidden>\n          <div id="deliveryRadiusNotice" class="delivery-radius-notice warning"><strong>📍 Entrega a domicilio únicamente dentro de 1 km de la sucursal</strong><span id="deliveryLocationStatus" class="delivery-location-status">Necesitamos validar la ubicación de este dispositivo para confirmar que estás cerca de la farmacia.</span><div class="delivery-location-actions"><button id="validateDeliveryLocation" type="button">Validar mi ubicación</button><span>Tu ubicación exacta no se guarda en el historial.</span></div></div>\n          <label>Dirección de entrega''')
r('<p>Conserva este folio para identificarlo.</p><div id="successOrderId" class="order-id">—</div>', '<p>Conserva este folio para identificarlo.</p><div id="successOrderId" class="order-id">—</div><div class="success-privacy-note">🔒 Tus datos de contacto no se muestran en el pedido finalizado. La dirección y la fotografía de entrega ya fueron retiradas de esta pantalla.</div>')
r("  const STORAGE_PROGRESS_DISMISS = 'mi_farmacia:progress_dismiss:v1';\n", "  const STORAGE_PROGRESS_DISMISS = 'mi_farmacia:progress_dismiss:v1';\n  const STORAGE_LOCATION_PERMISSION = 'mi_farmacia:location_permission:v1';\n  const STORAGE_ORDER_RATE = 'mi_farmacia:order_rate:v1';\n")
r("  const MAX_ORDER_QTY = 99;\n", "  const MAX_ORDER_QTY = 99;\n  const MAX_DELIVERY_DISTANCE_KM = 1;\n  const LOCATION_ACCURACY_LIMIT_M = 350;\n  const LOCATION_CACHE_MS = 3 * 60 * 1000;\n  const ORDER_SUBMIT_COOLDOWN_MS = 60 * 1000;\n")
r("historyOrderOpenId:'' };", "historyOrderOpenId:'', deviceLocation:null, deviceLocationAt:0, deliveryLocationCheck:null };")
marker="  function openStoreMaps(){const url=storeMapsUrl();if(!url){toast('La farmacia aún no ha publicado su ubicación.');return;}window.open(url,'_blank','noopener,noreferrer');}\n"
geo=r'''  function coordinatesFromMapsUrl(raw){const value=text(raw);if(!value)return null;const patterns=[/@(-?\d{1,2}(?:\.\d+)?),(-?\d{1,3}(?:\.\d+)?)/,/!3d(-?\d{1,2}(?:\.\d+)?)!4d(-?\d{1,3}(?:\.\d+)?)/,/[?&](?:q|query|ll)=(-?\d{1,2}(?:\.\d+)?)(?:%2C|,)(-?\d{1,3}(?:\.\d+)?)/i];for(const p of patterns){const m=value.match(p);if(!m)continue;const lat=Number(m[1]),lng=Number(m[2]);if(Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat)<=90&&Math.abs(lng)<=180)return{lat,lng};}return null;}
  function storeCoordinates(){const candidates=[state.store?.ubicacion,state.publication?.ubicacion,state.store,state.publication];for(const c of candidates){if(!c||typeof c!=='object')continue;const lat=Number(c.latitud??c.lat??c.latitude),lng=Number(c.longitud??c.lng??c.lon??c.longitude);if(Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat)<=90&&Math.abs(lng)<=180)return{lat,lng};}return coordinatesFromMapsUrl(storeMapsUrl());}
  function haversineKm(a,b){if(!a||!b)return Infinity;const rad=v=>Number(v)*Math.PI/180,R=6371,dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng),x=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(x)));}
  function locationStatus(message,type='warning'){const box=$('deliveryRadiusNotice'),status=$('deliveryLocationStatus');if(status)status.textContent=message||'';if(box){box.classList.remove('warning','ok','error');box.classList.add(type);}}
  function getDevicePosition({force=false}={}){if(!navigator.geolocation)return Promise.reject(new Error('Este dispositivo no permite usar ubicación.'));if(!force&&state.deviceLocation&&Date.now()-Number(state.deviceLocationAt||0)<LOCATION_CACHE_MS)return Promise.resolve(state.deviceLocation);return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(pos=>{const point={lat:Number(pos.coords.latitude),lng:Number(pos.coords.longitude),accuracy:Number(pos.coords.accuracy||0)};state.deviceLocation=point;state.deviceLocationAt=Date.now();resolve(point);},err=>reject(new Error(err?.code===1?'No autorizaste el uso de ubicación. Para entrega a domicilio es necesario permitirla.':err?.code===2?'No fue posible determinar tu ubicación. Activa la ubicación del dispositivo e inténtalo de nuevo.':'La validación de ubicación tardó demasiado. Inténtalo nuevamente.')),{enableHighAccuracy:true,timeout:12000,maximumAge:force?0:60000}));}
  async function ensureDeliveryLocation({force=false,quiet=false}={}){const store=storeCoordinates();if(!store){const result={ok:false,reason:'STORE_LOCATION_MISSING'};state.deliveryLocationCheck=result;if(!quiet)locationStatus('La farmacia todavía no ha publicado coordenadas precisas de su sucursal. Por ahora selecciona recoger en sucursal.','error');return result;}try{if(!quiet)locationStatus('Validando tu ubicación…','warning');const point=await getDevicePosition({force});const accuracy=Number(point.accuracy||0);if(accuracy>LOCATION_ACCURACY_LIMIT_M){const result={ok:false,reason:'LOW_ACCURACY',accuracy};state.deliveryLocationCheck=result;if(!quiet)locationStatus(`La ubicación tiene una precisión de aproximadamente ${Math.round(accuracy)} m. Activa ubicación precisa y vuelve a intentarlo.`,'error');return result;}const distanceKm=haversineKm(point,store),result={ok:distanceKm<=MAX_DELIVERY_DISTANCE_KM,distanceKm,accuracy,checkedAt:nowISO()};state.deliveryLocationCheck=result;if(!quiet){if(result.ok)locationStatus(`Ubicación validada: estás aproximadamente a ${Math.max(.01,distanceKm).toFixed(2)} km de la sucursal. Puedes solicitar entrega a domicilio.`,'ok');else locationStatus(`La entrega a domicilio está limitada a ${MAX_DELIVERY_DISTANCE_KM} km. Tu ubicación está aproximadamente a ${distanceKm.toFixed(2)} km de la sucursal.`,'error');}return result;}catch(error){const result={ok:false,reason:'PERMISSION',error:text(error?.message||error)};state.deliveryLocationCheck=result;if(!quiet)locationStatus(result.error,'error');return result;}}
  async function requestLocationOnActivation(){if(!navigator.geolocation||!storeCoordinates())return false;let permission='prompt';try{if(navigator.permissions?.query){const p=await navigator.permissions.query({name:'geolocation'});permission=p.state;}}catch(_){}const saved=readJsonStorage(STORAGE_LOCATION_PERMISSION,{});if(permission==='denied')return false;if(permission==='granted'){await ensureDeliveryLocation({quiet:true}).catch(()=>{});return true;}if(Number(saved?.askedAt||0)&&Date.now()-Number(saved.askedAt)<86400000)return false;writeJsonStorage(STORAGE_LOCATION_PERMISSION,{askedAt:Date.now(),status:'asked'});const result=await ensureDeliveryLocation({quiet:true}).catch(()=>({ok:false}));return !!result?.ok;}
'''
r(marker,marker+geo)
r("writeJsonStorage(STORAGE_CUSTOMER,{name,phone,updatedAt:nowISO()});$('welcomeModal').hidden=true;$('welcomeError').textContent='';if($('welcomeModal').hidden&&$('quantityModal').hidden&&$('checkoutModal').hidden&&$('successModal').hidden&&$('cartDrawer').hidden&&$('connectionPanel').hidden)document.body.style.overflow='';toast('Datos guardados en este dispositivo');", "writeJsonStorage(STORAGE_CUSTOMER,{name,phone,updatedAt:nowISO()});$('welcomeModal').hidden=true;$('welcomeError').textContent='';if($('welcomeModal').hidden&&$('quantityModal').hidden&&$('checkoutModal').hidden&&$('successModal').hidden&&$('cartDrawer').hidden&&$('connectionPanel').hidden)document.body.style.overflow='';toast('Datos listos para tu pedido');requestLocationOnActivation().catch(()=>{});")
r("  function deliveryType(){return document.querySelector('input[name=\"deliveryType\"]:checked')?.value||'RECOGER_SUCURSAL'}\n  function refreshDeliveryFields(){const home=deliveryType()==='DOMICILIO';$('pickupFields').hidden=home;$('homeDeliveryFields').hidden=!home;if(!home){$('checkoutMessage').textContent='';}}\n", r'''  function deliveryType(){return document.querySelector('input[name="deliveryType"]:checked')?.value||'RECOGER_SUCURSAL'}
  function refreshDeliveryFields(){const home=deliveryType()==='DOMICILIO';$('pickupFields').hidden=home;$('homeDeliveryFields').hidden=!home;if(!home){$('checkoutMessage').textContent='';state.deliveryLocationCheck=null;}else locationStatus(`Entrega disponible únicamente dentro de ${MAX_DELIVERY_DISTANCE_KM} km de la sucursal. Valida tu ubicación para continuar.`,'warning');}
  async function onDeliveryTypeChanged(){refreshDeliveryFields();if(deliveryType()!=='DOMICILIO')return;const result=await ensureDeliveryLocation({force:false});if(!result.ok)$('checkoutMessage').textContent='No podemos confirmar entrega a domicilio con esta ubicación. Puedes continuar seleccionando recoger en sucursal.';}
  function clearPrivateCustomerData(){for(const id of ['customerName','customerPhone','customerNote','deliveryAddress']){const el=$(id);if(el)el.value='';}clearFacade();state.deliveryLocationCheck=null;state.deviceLocation=null;state.deviceLocationAt=0;}
  function hasActiveLocalOrder(){return localOrders().some(o=>['NUEVO','EN_PROCESO','PREPARANDO','PREPARANDO_PEDIDO'].includes(text(o?.estado||'').toUpperCase()))}
  function orderRateRemaining(){const rate=readJsonStorage(STORAGE_ORDER_RATE,{}),elapsed=Date.now()-Number(rate?.lastSentAt||0);return Math.max(0,ORDER_SUBMIT_COOLDOWN_MS-elapsed)}
''')
s=s.replace("? `Entrega a domicilio${o.entrega?.direccion?` · ${esc(o.entrega.direccion)}`:''}`", "? `Entrega a domicilio`",1)
r("    if(!cartValues().length){$('checkoutMessage').textContent='El carrito está vacío.';return}\n    const entrega=tipo==='DOMICILIO'", "    if(!cartValues().length){$('checkoutMessage').textContent='El carrito está vacío.';return}\n    if(hasActiveLocalOrder()){$('checkoutMessage').textContent='Ya tienes un pedido activo. Espera a que la farmacia lo surta o cancele antes de enviar otro pedido desde este dispositivo.';return}\n    const restante=orderRateRemaining();if(restante>0){$('checkoutMessage').textContent=`Espera ${Math.ceil(restante/1000)} segundos antes de enviar otro pedido.`;return}\n    let verificacionUbicacion=null;if(tipo==='DOMICILIO'){verificacionUbicacion=await ensureDeliveryLocation({force:true});if(!verificacionUbicacion.ok){$('checkoutMessage').textContent=verificacionUbicacion.reason==='STORE_LOCATION_MISSING'?'La entrega a domicilio no está disponible hasta que la farmacia publique su ubicación precisa. Selecciona recoger en sucursal.':(verificacionUbicacion.error||`La entrega a domicilio solo está disponible dentro de ${MAX_DELIVERY_DISTANCE_KM} km de la sucursal.`);return}}\n    const entrega=tipo==='DOMICILIO'")
r("const contenidoCifrado=await encryptOrderContent({cliente:{nombre:name,telefono:phone},observaciones:note,entrega,items,piezas:totals.pieces,totalEstimado:Math.round(totals.total*100)/100});", "const entregaPrivada=tipo==='DOMICILIO'?{...entrega,validacionUbicacion:{validada:true,distanciaKm:Number(verificacionUbicacion?.distanceKm||0).toFixed(3),precisionMetros:Math.round(Number(verificacionUbicacion?.accuracy||0)),verificadaEn:verificacionUbicacion?.checkedAt||nowISO()}}:entrega;const contenidoCifrado=await encryptOrderContent({cliente:{nombre:name,telefono:phone},observaciones:note,entrega:entregaPrivada,items,piezas:totals.pieces,totalEstimado:Math.round(totals.total*100)/100});")
r("writeJsonStorage(STORAGE_CUSTOMER,{name,phone,updatedAt:nowISO()});localStorage.setItem('mi_farmacia:last_order',JSON.stringify({id,storeId:state.storeId,createdAt:creadoEn}));addLocalOrder({id,storeId:state.storeId,token,createdAt:creadoEn,estado:'NUEVO',mensaje:statusPayload.mensaje,entrega:{tipo:entrega.tipo,fechaEstimada:entrega.fechaEstimada||'',horaEstimada:entrega.horaEstimada||'',direccion:entrega.direccion||''},items:items.map(it=>({codigo:it.codigo,nombre:it.nombre,presentacion:it.presentacion,cantidad:Number(it.cantidad||0),precioUnitario:Number(it.precioUnitario||0),importe:Number(it.importe||0)})),pieces:totals.pieces,total:Math.round(totals.total*100)/100});state.cart.clear();persistCart();renderCart();clearFacade();closeModal('checkoutModal');$('successOrderId').textContent=id;$('successModal').hidden=false;document.body.style.overflow='hidden';refreshOrderStatuses();", "writeJsonStorage(STORAGE_CUSTOMER,{name,phone,updatedAt:nowISO()});localStorage.setItem('mi_farmacia:last_order',JSON.stringify({id,storeId:state.storeId,createdAt:creadoEn}));writeJsonStorage(STORAGE_ORDER_RATE,{lastSentAt:Date.now(),orderId:id});addLocalOrder({id,storeId:state.storeId,token,createdAt:creadoEn,estado:'NUEVO',mensaje:statusPayload.mensaje,entrega:{tipo:entrega.tipo,fechaEstimada:entrega.fechaEstimada||'',horaEstimada:entrega.horaEstimada||''},items:items.map(it=>({codigo:it.codigo,nombre:it.nombre,presentacion:it.presentacion,cantidad:Number(it.cantidad||0),precioUnitario:Number(it.precioUnitario||0),importe:Number(it.importe||0)})),pieces:totals.pieces,total:Math.round(totals.total*100)/100});state.cart.clear();persistCart();renderCart();clearPrivateCustomerData();closeModal('checkoutModal');$('successOrderId').textContent=id;$('successModal').hidden=false;document.body.style.overflow='hidden';refreshOrderStatuses();")
r("$('deliveryPickup').addEventListener('change',refreshDeliveryFields);$('deliveryHome').addEventListener('change',refreshDeliveryFields);$('deliveryFacade').addEventListener('change',onFacadeSelected);", "$('deliveryPickup').addEventListener('change',onDeliveryTypeChanged);$('deliveryHome').addEventListener('change',onDeliveryTypeChanged);$('validateDeliveryLocation')?.addEventListener('click',()=>ensureDeliveryLocation({force:true}));$('deliveryFacade').addEventListener('change',onFacadeSelected);")
r("      await loadCatalog({quiet:!!state.products.length,forceNetwork:true});\n      loadMasterImageCatalog({force:true}).catch(()=>{});", "      await loadCatalog({quiet:!!state.products.length,forceNetwork:true});\n      if($('welcomeModal')?.hidden)setTimeout(()=>requestLocationOnActivation().catch(()=>{}),700);\n      loadMasterImageCatalog({force:true}).catch(()=>{});")
p.write_text(s,encoding='utf-8')
print('ok')
