from pathlib import Path

p=Path('docs/index.html')
s=p.read_text(encoding='utf-8')

def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit('No se encontró: '+label)
    s=s.replace(old,new,1)

rep('class="brand-logo">','id="brandLogo" class="brand-logo">','brand logo id')
rep('.brand-logo{width:38px;height:38px;border-radius:12px;object-fit:contain;box-shadow:0 7px 18px rgba(0,70,125,.13)}','.brand-logo{width:38px;height:38px;border-radius:12px;object-fit:contain;box-shadow:0 7px 18px rgba(0,70,125,.13)}.brand-logo.custom-store-image{object-fit:cover;border:1px solid #d7e4ef}','brand css')
rep('.state-card strong{color:#42566d}.state-icon{font-size:2.6rem}', '.state-card strong{color:#42566d}.state-icon{font-size:2.6rem}.paused-state{min-height:360px;padding:30px 20px}.paused-state .state-icon{font-size:3.3rem}.paused-state strong{font-size:1.15rem;color:#8b5c00}.paused-state span{max-width:520px;font-size:.86rem;line-height:1.55}.cart-button:disabled{opacity:.45;cursor:not-allowed}', 'pause css')
rep('    <section id="loadingState" class="state-card"><div class="spinner"></div><strong>Cargando catálogo…</strong><span>Consultando disponibilidad y precios.</span></section>', '    <section id="pausedState" class="state-card paused-state" hidden><div class="state-icon">🛠️</div><strong>Tienda pausada por mantenimiento</strong><span>Pronto estaremos en línea. Gracias por tu comprensión.</span></section>\n    <section id="loadingState" class="state-card"><div class="spinner"></div><strong>Cargando catálogo…</strong><span>Consultando disponibilidad y precios.</span></section>', 'paused markup')
rep("  function refreshConnectionInfo(){\n    const nombre=text(state.store?.nombreActivo||state.store?.nombre||state.publication?.nombre||CONFIG_FILE.nombreTienda||'Mi Farmacia');", "  const DEFAULT_BRAND_LOGO_SRC=$('brandLogo')?.src||'';\n  function storePaused(){return state.store?.pausada===true;}\n  function refreshStoreImage(){const img=$('brandLogo');if(!img)return;const personalizada=text(state.store?.imagenFarmaciaUrl||'');const valida=/^data:image\\/(?:jpeg|jpg|png|webp);base64,/i.test(personalizada);img.src=valida?personalizada:DEFAULT_BRAND_LOGO_SRC;img.classList.toggle('custom-store-image',valida);img.alt=valida?`Imagen de ${text(state.store?.nombreActivo||state.store?.nombre||'la farmacia')}`:'Mi Farmacia';}\n  function refreshStoreAvailability(){\n    const pausada=storePaused();const paused=$('pausedState');if(paused)paused.hidden=!pausada;\n    const search=document.querySelector('.search-shell');if(search)search.hidden=pausada;\n    const grid=$('productGrid');if(grid)grid.hidden=pausada;\n    const loadWrap=$('loadMoreProducts')?.parentElement;if(loadWrap)loadWrap.hidden=pausada;\n    const cart=$('cartButton');if(cart){cart.disabled=pausada;cart.title=pausada?'Tienda pausada por mantenimiento':'';}\n    if(pausada){$('loadingState').hidden=true;$('emptyState').hidden=true;closeCart();if(!$('quantityModal').hidden)closeModal('quantityModal');if(!$('checkoutModal').hidden)closeModal('checkoutModal');}\n  }\n  function refreshConnectionInfo(){\n    const nombre=text(state.store?.nombreActivo||state.store?.nombre||state.publication?.nombre||CONFIG_FILE.nombreTienda||'Mi Farmacia');", 'store helpers')
rep("    $('pickupStoreAddress').textContent=direccion;\n    const online=!!(state.store&&state.firebaseUrl&&!state.lastError);\n    $('connectionState').textContent=online?'Conectado al sistema principal':(navigator.onLine?'Sin sincronizar':'Sin internet');", "    $('pickupStoreAddress').textContent=direccion;\n    refreshStoreImage();refreshStoreAvailability();\n    const online=!!(state.store&&state.firebaseUrl&&!state.lastError);\n    $('connectionState').textContent=online?(storePaused()?'Tienda pausada por mantenimiento':'Conectado al sistema principal'):(navigator.onLine?'Sin sincronizar':'Sin internet');", 'refresh store state')
rep("      if(metaResultado.status!=='fulfilled') throw metaResultado.reason;\n      if(tiendaResultado.status!=='fulfilled') throw tiendaResultado.reason;\n      const meta=metaResultado.value||{};\n\n      if(Number(meta.version||0)!==2||!Number(meta.revision||0)) throw new Error('El catálogo todavía no ha sido sincronizado con la versión móvil actual.');", "      if(metaResultado.status!=='fulfilled') throw metaResultado.reason;\n      if(tiendaResultado.status!=='fulfilled') throw tiendaResultado.reason;\n      const meta=metaResultado.value||{};\n      refreshConnectionInfo();\n      if(storePaused()){state.lastError='';setStatus(true,'Mantenimiento');$('loadingState').hidden=true;refreshStoreAvailability();return true;}\n\n      if(Number(meta.version||0)!==2||!Number(meta.revision||0)) throw new Error('El catálogo todavía no ha sido sincronizado con la versión móvil actual.');", 'paused load')
rep('  function openQuantity(id){ const p=state.productMap.get(id); if(!p)return;', "  function openQuantity(id){ if(storePaused()){toast('Tienda pausada por mantenimiento. Pronto estaremos en línea.');return;} const p=state.productMap.get(id); if(!p)return;", 'quantity guard')
rep('  function openCheckout(){if(!cartValues().length)return;', "  function openCheckout(){if(storePaused()){toast('Tienda pausada por mantenimiento. Pronto estaremos en línea.');return;}if(!cartValues().length)return;", 'checkout guard')
rep('  async function submitOrder(){\n    if(state.loading)return;', "  async function submitOrder(){\n    if(storePaused()){ $('checkoutMessage').textContent='Tienda pausada por mantenimiento. Pronto estaremos en línea.'; return; }\n    if(state.loading)return;", 'submit guard')

for needle in ['id="brandLogo"','pausedState','storePaused()','imagenFarmaciaUrl','Mantenimiento']:
    if needle not in s: raise SystemExit('Faltó aplicar '+needle)
p.write_text(s,encoding='utf-8')
